# Generated by Django 3.2.4 on 2021-06-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.CharField(max_length=255),
        ),
    ]
